# Generated by Django 3.0.6 on 2020-05-24 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0002_auto_20200523_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='rss',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userpost',
            unique_together={('user', 'post')},
        ),
    ]
