# Generated by Django 3.0.6 on 2020-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('feeds', '0003_auto_20200524_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
